controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    countB += 1
    countReporter.say(countB)
    for (let index = 0; index < countB; index++) {
        music.playTone(262, music.beat(BeatFraction.Quarter))
    }
})
let countReporter: Sprite = null
let countB = 0
countB = 0
countReporter = sprites.create(img`
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff......ccc.
    .ffefbf44fbfeff....cddc.
    .ffefbf44fbfeff...cddc..
    .fee4dddddd4eef.ccddc...
    fdfeeddddd4eeffecddc....
    fbffee4444ee4fddccc.....
    fbf4f222222f1edde.......
    fcf.f222222f44ee........
    .ff.f445544f............
    ....ffffffff............
    .....ff..ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
